const STOCK_LESSONS = [
  {
    id: 'what-is-a-stock', title: 'What is a Stock?', category: 'fundamentals', difficulty: 'beginner', estimatedMinutes: 8, xpReward: 50,
    sections: [
      { type: 'text', content: '<h3>Ownership in a Company</h3><p>A stock represents a fractional ownership stake in a company. When you buy a share of Apple (AAPL), you literally own a tiny piece of the company — its assets, its earnings, and its future growth.</p><p>Companies issue stock to raise capital. Instead of borrowing money (debt), they sell ownership stakes to investors. This happens first in an <strong>IPO (Initial Public Offering)</strong>, and then shares trade freely on exchanges.</p>' },
      { type: 'text', content: '<h3>Stock Exchanges</h3><p>Stocks trade on exchanges — organized marketplaces where buyers and sellers meet electronically. The two biggest in the US:</p><ul><li><strong>NYSE (New York Stock Exchange)</strong> — The largest by market cap. Trading hours: 9:30 AM to 4:00 PM ET.</li><li><strong>NASDAQ</strong> — Tech-heavy, fully electronic. Home to AAPL, MSFT, AMZN, NVDA, TSLA.</li></ul><p>When you place a buy order, your broker routes it to the exchange. A market maker matches it with a sell order. This happens in milliseconds.</p>' },
      { type: 'interactive-chart', config: { ticker: 'AAPL', title: 'Apple (AAPL) — Your First Chart', description: 'This is a candlestick chart. Each candle represents one trading day. Hover over candles to see Open, High, Low, Close (OHLC) prices and volume.' } },
      { type: 'key-concept', title: 'Bull vs Bear Markets', content: 'A <strong>bull market</strong> is when prices rise 20%+ from a recent low. A <strong>bear market</strong> is when prices fall 20%+ from a recent high. These terms come from how each animal attacks — bulls thrust horns up, bears swipe paws down.' },
      { type: 'text', content: '<h3>Why Stock Prices Move</h3><p>A stock price reflects what buyers will pay and sellers will accept. Prices move based on:</p><ul><li><strong>Earnings</strong> — Did the company make more or less money than expected?</li><li><strong>News</strong> — Product launches, lawsuits, management changes</li><li><strong>Macro factors</strong> — Interest rates, inflation, GDP growth</li><li><strong>Sentiment</strong> — Fear and greed drive short-term swings</li></ul>' }
    ]
  },
  {
    id: 'reading-price-charts', title: 'Reading Price Charts', category: 'technical-analysis', difficulty: 'beginner', estimatedMinutes: 10, xpReward: 60,
    sections: [
      { type: 'text', content: '<h3>Three Types of Price Charts</h3><p>Traders use charts to visualize price history and spot patterns. The three most common:</p><ol><li><strong>Line Chart</strong> — Connects closing prices. Simplest view, good for overall trend.</li><li><strong>Bar Chart (OHLC)</strong> — Each bar shows Open, High, Low, Close. More data than a line chart.</li><li><strong>Candlestick Chart</strong> — Like bar charts but with a filled/hollow body. The most popular choice among traders.</li></ol>' },
      { type: 'text', content: '<h3>Anatomy of a Candlestick</h3><p>Each candlestick tells a story about the battle between buyers and sellers:</p><ul><li><strong>Body</strong> — The thick part. Shows the range between open and close.</li><li><strong>Wicks/Shadows</strong> — The thin lines above and below. Show the high and low.</li><li><strong>Green candle</strong> — Close > Open (buyers won)</li><li><strong>Red candle</strong> — Close < Open (sellers won)</li></ul><p>Long bodies = strong conviction. Long wicks = rejection at that price level.</p>' },
      { type: 'interactive-chart', config: { ticker: 'TSLA', title: 'Tesla (TSLA) — Reading Candlesticks', description: 'Notice the large green and red candles. Big green = strong buying pressure. Big red = strong selling. Long upper wicks mean sellers pushed price back down.' } },
      { type: 'key-concept', title: 'Volume Confirms Price', content: 'A price move on high volume is more significant than on low volume. If a stock breaks to a new high on 3x average volume, that is a strong signal. The same breakout on low volume is suspicious and may fail.' },
      { type: 'text', content: '<h3>Timeframes</h3><p>Charts can show different timeframes:</p><ul><li><strong>1-minute, 5-minute</strong> — Day traders</li><li><strong>1-hour, 4-hour</strong> — Swing traders</li><li><strong>Daily</strong> — Most common for analysis</li><li><strong>Weekly, Monthly</strong> — Long-term investors</li></ul><p>The same stock can look bullish on a daily chart and bearish on a 5-minute chart. Always consider the timeframe.</p>' }
    ]
  },
  {
    id: 'volume-analysis', title: 'Volume & What It Tells You', category: 'technical-analysis', difficulty: 'beginner', estimatedMinutes: 10, xpReward: 60,
    sections: [
      { type: 'text', content: '<h3>What is Volume?</h3><p>Volume is the number of shares traded in a given period. It is the most important confirmation tool in technical analysis.</p><p>Think of volume as the <strong>conviction</strong> behind a price move. Price tells you WHAT happened. Volume tells you HOW MUCH conviction was behind it.</p>' },
      { type: 'interactive-chart', config: { ticker: 'NVDA', title: 'NVIDIA (NVDA) — Volume Analysis', description: 'The bars at the bottom show volume. Notice how volume spikes on big price moves. Green bars = up days, red = down days.', showVolume: true } },
      { type: 'key-concept', title: 'Volume Signals', content: '<strong>High volume + price up</strong> = strong buying (bullish). <strong>High volume + price down</strong> = strong selling (bearish). <strong>Low volume + price up</strong> = weak rally (suspicious). <strong>Low volume + price down</strong> = lack of sellers (potentially bullish).' },
      { type: 'text', content: '<h3>On-Balance Volume (OBV)</h3><p>OBV is a cumulative indicator. It adds volume on up days and subtracts on down days. If OBV is trending up while price is flat, it suggests accumulation — smart money buying before a move up.</p><p><strong>Volume Spike Rule:</strong> If today\'s volume is 2x or more the 20-day average, pay attention. Combine this with price action for trading signals.</p>' },
      { type: 'text', content: '<h3>How a Real Trader Uses Volume</h3><p>Suppose you are watching NVDA and it has been consolidating between $800 and $850 for two weeks. One morning, the stock breaks above $850 on volume that is 3x the 20-day average. A volume-aware trader treats this as a high-conviction breakout because the surge in participation confirms that institutional money is driving the move, not just a handful of retail orders.</p><p>Conversely, if NVDA drifts above $850 on below-average volume, an experienced trader would be skeptical. The breakout lacks conviction and is more likely to fail. Many traders will wait for a volume-confirmed retest of the breakout level before committing capital.</p><p>Volume also matters on pullbacks. If a stock pulls back to a key moving average on declining volume, it suggests sellers are drying up and the uptrend is likely to continue. Heavy volume on the pullback, on the other hand, signals genuine distribution and a potential trend change.</p>' },
      { type: 'comparison-table', headers: ['Volume Pattern', 'What It Means', 'Trader Action'], rows: [['Breakout on high volume', 'Strong conviction, likely to follow through', 'Enter in the direction of the breakout with a stop below the breakout level'], ['Breakout on low volume', 'Weak conviction, likely a false breakout', 'Wait for a retest or skip the trade entirely'], ['Pullback on declining volume', 'Sellers drying up, trend intact', 'Look for entries near support or a moving average'], ['Pullback on rising volume', 'Distribution, potential trend reversal', 'Tighten stops or reduce position size'], ['Volume spike on a reversal candle', 'Capitulation or climax buying', 'Watch for follow-through the next day before acting']] },
      { type: 'key-concept', title: 'Pro Tips for Volume Analysis', content: 'Always compare current volume to its own average, not to another stock. NVDA trading 50 million shares may be normal, while the same volume on a small-cap would be extraordinary. Use the 20-day average volume as your baseline. Also pay attention to volume at specific price levels (Volume Profile), which reveals where the most trading activity occurred and highlights support and resistance zones that pure price charts miss.' }
    ]
  },
  {
    id: 'support-resistance', title: 'Support & Resistance', category: 'technical-analysis', difficulty: 'beginner', estimatedMinutes: 12, xpReward: 75,
    sections: [
      { type: 'text', content: '<h3>The Foundation of Technical Analysis</h3><p>Support and resistance are the most fundamental concepts in charting. Every other pattern builds on them.</p><ul><li><strong>Support</strong> — A price level where buying pressure prevents further decline. Think of it as a floor.</li><li><strong>Resistance</strong> — A price level where selling pressure prevents further advance. Think of it as a ceiling.</li></ul><p>These levels form because traders remember prices. If you bought at $150 and it dropped to $130, you might sell at $150 when it comes back — creating resistance.</p>' },
      { type: 'interactive-chart', config: { ticker: 'MSFT', title: 'Microsoft (MSFT) — Support & Resistance', description: 'Look for price levels where the stock bounces multiple times (support) or gets rejected multiple times (resistance). The more touches, the stronger the level.' } },
      { type: 'key-concept', title: 'Role Reversal', content: 'When support breaks, it often becomes resistance. When resistance breaks, it often becomes support. This is called <strong>role reversal</strong> and is one of the most reliable patterns in trading.' },
      { type: 'text', content: '<h3>How to Identify Key Levels</h3><ol><li><strong>Multiple touches</strong> — At least 2-3 bounces from the same level</li><li><strong>Round numbers</strong> — $100, $200, $500 act as psychological S/R</li><li><strong>Previous highs/lows</strong> — Last week high, 52-week high, all-time high</li><li><strong>Gap fills</strong> — Gaps in price often act as magnets</li></ol><p>Support and resistance are <em>zones</em>, not exact prices. A stock with support at $150 might bounce from $149.50 or $150.80.</p>' },
      { type: 'text', content: '<h3>Common Mistakes with Support and Resistance</h3><ul><li><strong>Drawing too many levels</strong> — If your chart looks like a barcode, you have too many lines. Focus on the 2-3 most significant levels where price reacted strongly and recently. Quality matters more than quantity.</li><li><strong>Treating levels as exact prices</strong> — Support at $150 does not mean the stock will bounce at exactly $150.00. Think in zones of $1-2 around the level. Setting a stop at exactly $150.00 will get you stopped out on normal volatility.</li><li><strong>Ignoring the timeframe</strong> — A support level on a daily chart is far more significant than one on a 5-minute chart. Weekly and monthly levels carry the most weight because they represent decisions by the largest pool of market participants.</li><li><strong>Fighting a strong trend</strong> — Buying at support in a strong downtrend is called catching a falling knife. Support levels break in downtrends. Wait for confirmation that buyers have actually stepped in before committing capital.</li></ul>' },
      { type: 'key-concept', title: 'Pro Tips for Support and Resistance', content: 'The strongest support and resistance levels are ones where multiple factors converge at the same price. For example, a round number ($200) that also aligns with the 200-day moving average and was a previous breakout level is a much stronger zone than any single factor alone. Also remember that the longer a support or resistance level holds, the more significant the eventual break will be. A resistance level that has rejected price five times over six months will produce a powerful move when it finally breaks.' }
    ]
  },
  {
    id: 'moving-averages', title: 'Moving Averages (SMA & EMA)', category: 'technical-analysis', difficulty: 'beginner', estimatedMinutes: 12, xpReward: 75,
    sections: [
      { type: 'text', content: '<h3>Smoothing Out the Noise</h3><p>A moving average smooths price data by creating a constantly updated average. It helps you see the trend by filtering out day-to-day noise.</p><ul><li><strong>SMA (Simple Moving Average)</strong> — Equal weight to all periods. The 20-day SMA = average closing price of last 20 days.</li><li><strong>EMA (Exponential Moving Average)</strong> — More weight on recent prices. Reacts faster to new data.</li></ul>' },
      { type: 'interactive-chart', config: { ticker: 'AAPL', title: 'Apple (AAPL) — Moving Averages', description: 'Adjust the slider to change the SMA period. Shorter periods (10-20) hug price tightly. Longer periods (100-200) show broader trend.', indicators: ['sma'], controls: [{ type: 'slider', label: 'SMA Period', min: 5, max: 200, default: 20, id: 'smaPeriod' }] } },
      { type: 'key-concept', title: 'Golden Cross & Death Cross', content: 'The <strong>Golden Cross</strong> occurs when the 50-day SMA crosses ABOVE the 200-day SMA — a bullish signal. The <strong>Death Cross</strong> is the opposite — the 50-day crosses BELOW the 200-day, signaling bearish momentum.' },
      { type: 'comparison-table', headers: ['Feature', 'SMA', 'EMA'], rows: [['Weight', 'Equal weight to all periods', 'More weight to recent prices'], ['Lag', 'More lag (slower)', 'Less lag (faster)'], ['False Signals', 'Fewer', 'More but catches turns faster'], ['Best For', 'Long-term trends', 'Short-term signals'], ['Popular Periods', '20, 50, 100, 200', '9, 12, 21, 26']] },
      { type: 'text', content: '<h3>MAs as Dynamic Support/Resistance</h3><p>In an uptrend, the 20-day or 50-day MA often acts as dynamic support — the stock pulls back to the MA and bounces. In a downtrend, the MA acts as resistance.</p><p><strong>Pro tip:</strong> Institutions watch the 200-day SMA closely. A stock trading above its 200-day is considered in a long-term uptrend.</p>' }
    ]
  },
  {
    id: 'rsi-indicator', title: 'RSI (Relative Strength Index)', category: 'technical-analysis', difficulty: 'intermediate', estimatedMinutes: 12, xpReward: 80,
    sections: [
      { type: 'text', content: '<h3>Measuring Momentum</h3><p>The RSI is a momentum oscillator that measures the speed and magnitude of price movements on a scale from 0 to 100. Developed by J. Welles Wilder in 1978.</p><ul><li><strong>RSI > 70</strong> — Overbought (potentially due for a pullback)</li><li><strong>RSI < 30</strong> — Oversold (potentially due for a bounce)</li><li><strong>RSI = 50</strong> — Neutral</li></ul><p>The standard period is 14 days.</p>' },
      { type: 'interactive-chart', config: { ticker: 'TSLA', title: 'Tesla (TSLA) — RSI Analysis', description: 'The RSI subplot oscillates between 0-100. Shaded zones show overbought (>70) and oversold (<30) areas.', indicators: ['rsi'], showRSI: true, controls: [{ type: 'slider', label: 'RSI Period', min: 5, max: 30, default: 14, id: 'rsiPeriod' }] } },
      { type: 'key-concept', title: 'RSI Divergence', content: '<strong>Bullish divergence</strong>: Price makes a lower low, but RSI makes a higher low — momentum is shifting up. <strong>Bearish divergence</strong>: Price makes a higher high, but RSI makes a lower high — momentum is fading. Divergences are among the most reliable signals RSI produces.' },
      { type: 'text', content: '<h3>Common Mistakes with RSI</h3><ul><li><strong>Do not blindly buy at RSI 30</strong> — In a strong downtrend, RSI can stay oversold for weeks.</li><li><strong>Context matters</strong> — RSI 70 in a strong uptrend is normal, not necessarily a sell signal.</li><li><strong>Combine with price action</strong> — RSI works best when confirmed by candlestick patterns or S/R levels.</li></ul>' },
      { type: 'text', content: '<h3>How a Real Trader Uses RSI</h3><p>Consider a scenario where TSLA has pulled back 15% over two weeks and RSI drops to 28. A beginner might rush to buy because "it is oversold." An experienced trader would wait for confirmation. They look for RSI to start turning up from below 30 — not just touching it, but forming a higher low on the RSI itself. They then check the daily chart for a bullish candlestick pattern at a key support level.</p><p>If all three conditions align — RSI turning up from oversold, bullish candle pattern, and price at a known support zone — the trader enters with a stop below the recent low. This multi-factor approach dramatically improves the probability compared to trading RSI alone.</p><p>For swing traders, a useful RSI technique is the "50-line bounce." In a strong uptrend, RSI rarely drops below 40-50. When it pulls back to the 40-50 zone and bounces, it signals the uptrend is intact and the pullback is a buying opportunity. If RSI breaks below 40 in what you thought was an uptrend, the trend may be weakening.</p>' },
      { type: 'comparison-table', headers: ['RSI Reading', 'Market Context', 'Interpretation', 'Action'], rows: [['Below 30', 'Downtrend', 'Can stay oversold for weeks; trend is strong to the downside', 'Do not buy blindly; wait for trend reversal confirmation'], ['Below 30', 'Uptrend pullback', 'Likely oversold bounce coming', 'Look for bullish candle and support confluence to enter long'], ['40-50', 'Uptrend', 'Healthy pullback; trend intact', 'Buy the dip with stop below the swing low'], ['Above 70', 'Strong uptrend', 'Momentum is strong; overbought is normal', 'Hold positions; do not short just because RSI is high'], ['Above 70', 'Extended rally after long base', 'Potential exhaustion', 'Tighten stops and watch for bearish divergence']] },
      { type: 'key-concept', title: 'Pro Tips for RSI', content: 'Adjust RSI settings based on your trading timeframe. The default 14-period works well for daily charts. Shorter-term traders often use RSI(7) for more responsive signals, while position traders may prefer RSI(21) for smoother readings. Also consider using RSI on multiple timeframes simultaneously. If the weekly RSI is above 50 (bullish trend) and the daily RSI just bounced from 30, that is a much higher-probability long entry than a daily RSI bounce in a weekly downtrend.' }
    ]
  },
  {
    id: 'macd-indicator', title: 'MACD — Trend & Momentum', category: 'technical-analysis', difficulty: 'intermediate', estimatedMinutes: 12, xpReward: 80,
    sections: [
      { type: 'text', content: '<h3>The MACD Explained</h3><p>MACD (Moving Average Convergence Divergence) is both a trend and momentum indicator. It shows the relationship between two EMAs.</p><ul><li><strong>MACD Line</strong> = 12-period EMA minus 26-period EMA</li><li><strong>Signal Line</strong> = 9-period EMA of the MACD Line</li><li><strong>Histogram</strong> = MACD Line minus Signal Line</li></ul>' },
      { type: 'interactive-chart', config: { ticker: 'AMZN', title: 'Amazon (AMZN) — MACD Analysis', description: 'MACD subplot: blue=MACD line, orange=signal, green/red bars=histogram. Crossovers generate signals.', indicators: ['macd'], showMACD: true } },
      { type: 'key-concept', title: 'MACD Signals', content: '<strong>Bullish crossover</strong>: MACD crosses ABOVE signal line — buy signal. <strong>Bearish crossover</strong>: MACD crosses BELOW signal line — sell signal. <strong>Histogram growing</strong>: Momentum increasing. <strong>Histogram shrinking</strong>: Momentum fading (early warning).' },
      { type: 'text', content: '<h3>MACD vs RSI</h3><p>RSI measures <em>how fast</em> price is moving. MACD measures <em>trend direction</em> and momentum. They complement each other. Use MACD for trend and crossover signals. Use RSI for overbought/oversold extremes. When both agree (MACD bullish cross + RSI bouncing from 30), the signal is stronger.</p>' },
      { type: 'text', content: '<h3>Common Mistakes with MACD</h3><ul><li><strong>Trading every crossover</strong> — In choppy, sideways markets, MACD will produce numerous crossovers that lead to whipsaw losses. Only trade MACD crossovers when the stock is trending. If the MACD line is hovering near zero and crossing back and forth, the market is range-bound and MACD signals are unreliable.</li><li><strong>Ignoring the histogram</strong> — Many traders only watch for crossovers and miss the histogram, which is actually the earliest warning signal. When the histogram starts shrinking, momentum is fading even before the crossover happens. This gives you a head start on exits.</li><li><strong>Using default settings blindly</strong> — The standard 12/26/9 settings work well for daily charts, but they lag on shorter timeframes. Day traders sometimes use 3/10/16 for faster signals. Test different settings on your specific timeframe before committing real capital.</li></ul>' },
      { type: 'comparison-table', headers: ['Indicator', 'Type', 'Best For', 'Weakness'], rows: [['MACD', 'Trend and momentum', 'Identifying trend direction and crossover entries', 'Lags in fast markets; generates false signals in ranges'], ['RSI', 'Momentum oscillator', 'Identifying overbought/oversold extremes and divergences', 'Can stay overbought/oversold for extended periods in strong trends'], ['Bollinger Bands', 'Volatility', 'Identifying squeezes, mean reversion, and band walks', 'Does not indicate direction; requires context for interpretation'], ['Moving Averages', 'Trend', 'Defining trend direction and dynamic support/resistance', 'Lagging indicator; slow to react to sudden reversals']] },
      { type: 'key-concept', title: 'Pro Tips for MACD', content: 'The most powerful MACD signal is divergence combined with a crossover. If the stock makes a new high but MACD makes a lower high (bearish divergence), and then MACD crosses below its signal line, that is a high-probability sell signal. The divergence shows weakening momentum and the crossover confirms the shift. Also look at where the crossover occurs relative to the zero line. A bullish crossover above zero is a continuation signal in an uptrend. A bullish crossover below zero is a potential trend reversal — higher reward but also higher risk.' }
    ]
  },
  {
    id: 'bollinger-bands', title: 'Bollinger Bands', category: 'technical-analysis', difficulty: 'intermediate', estimatedMinutes: 12, xpReward: 80,
    sections: [
      { type: 'text', content: '<h3>Volatility Envelope</h3><p>Bollinger Bands consist of three lines plotted on a price chart:</p><ul><li><strong>Middle Band</strong> = 20-period SMA</li><li><strong>Upper Band</strong> = Middle + 2 standard deviations</li><li><strong>Lower Band</strong> = Middle - 2 standard deviations</li></ul><p>About 95% of price action falls within the bands. When bands are wide, volatility is high. When bands are narrow, volatility is low.</p>' },
      { type: 'interactive-chart', config: { ticker: 'SPY', title: 'S&P 500 (SPY) — Bollinger Bands', description: 'Watch for band squeezes (narrow bands) which often precede big moves. Price touching the upper band is not automatically a sell signal.' } },
      { type: 'key-concept', title: 'The Bollinger Squeeze', content: 'When the bands contract to their narrowest width in months, it signals a <strong>squeeze</strong> — a period of low volatility that typically precedes a large move. The direction of the breakout determines the trade. Combine with volume for confirmation.' },
      { type: 'text', content: '<h3>Trading with Bollinger Bands</h3><p><strong>Mean Reversion</strong>: In sideways markets, price tends to bounce between the bands. Buy near the lower band, sell near the upper band.</p><p><strong>Trend Following</strong>: In strong trends, price "rides" the upper band (uptrend) or lower band (downtrend). This is called a Bollinger Band walk and is NOT a reversal signal.</p><p><strong>%B Indicator</strong>: Measures where price is relative to the bands. %B = (Price - Lower Band) / (Upper - Lower). Above 1 = above upper band. Below 0 = below lower band.</p>' },
      { type: 'text', content: '<h3>Common Mistakes with Bollinger Bands</h3><ul><li><strong>Selling every touch of the upper band</strong> — In a strong uptrend, price can "walk" along the upper band for weeks. Selling at the upper band in a trend means you are shorting a strong stock. Only use band touches as reversal signals in range-bound markets.</li><li><strong>Ignoring the bandwidth</strong> — The distance between the bands (bandwidth) tells you about volatility. Narrow bands mean low volatility and a big move is coming. Wide bands mean high volatility that may be peaking. Many traders watch for squeezes but forget to monitor when bands are abnormally wide, which often precedes a return to the mean.</li><li><strong>Using bands in isolation</strong> — A touch of the lower band is more significant if it occurs at a known support level and RSI is oversold. Without confirming signals, band touches alone have a poor win rate.</li></ul>' },
      { type: 'key-concept', title: 'Pro Tips for Bollinger Bands', content: 'One of the most reliable Bollinger Band setups is the "squeeze breakout." When the bands contract to their narrowest point in at least 6 months, mark the upper and lower bands. Place a buy-stop above the upper band and a sell-stop below the lower band, then let the market tell you the direction. Cancel the unfilled order once one side triggers. Combine this with volume — a squeeze breakout on high volume is much more trustworthy. Also experiment with different settings: 20-period / 2 standard deviations is the default, but some traders use 10-period / 1.5 deviations for shorter-term trading or 50-period / 2.5 deviations for a broader view.' }
    ]
  },
  {
    id: 'fibonacci-retracements', title: 'Fibonacci Retracements', category: 'technical-analysis', difficulty: 'intermediate', estimatedMinutes: 12, xpReward: 85,
    sections: [
      { type: 'text', content: '<h3>The Golden Ratio in Markets</h3><p>Fibonacci retracements are horizontal lines that indicate where support and resistance are likely to occur. They are based on the Fibonacci sequence and the golden ratio (1.618).</p><p>Key Fibonacci levels:</p><ul><li><strong>23.6%</strong> — Shallow retracement (strong trend)</li><li><strong>38.2%</strong> — Moderate pullback</li><li><strong>50.0%</strong> — Not a Fibonacci number, but widely watched</li><li><strong>61.8%</strong> — The golden ratio. Most important level</li><li><strong>78.6%</strong> — Deep retracement (trend may be weakening)</li></ul>' },
      { type: 'interactive-chart', config: { ticker: 'NVDA', title: 'NVIDIA (NVDA) — Fibonacci Levels', description: 'In a strong uptrend, pullbacks often find support near the 38.2% or 61.8% retracement levels. These levels act as natural support zones.' } },
      { type: 'key-concept', title: 'Confluence is Power', content: 'A Fibonacci level alone is moderately useful. But when it aligns with other factors — a moving average, a support level, a round number, or high volume — it becomes very powerful. This alignment is called <strong>confluence</strong>. Always look for 2+ factors agreeing at the same price.' },
      { type: 'text', content: '<h3>How to Draw Fibonacci Retracements</h3><p>For an <strong>uptrend</strong>: Draw from the swing low to the swing high. The retracement levels show where pullbacks may find support.</p><p>For a <strong>downtrend</strong>: Draw from the swing high to the swing low. The levels show where bounces may find resistance.</p><p>Fibonacci extensions (127.2%, 161.8%) can project profit targets beyond the original move.</p>' }
    ]
  },
  {
    id: 'chart-patterns', title: 'Chart Patterns', category: 'technical-analysis', difficulty: 'intermediate', estimatedMinutes: 15, xpReward: 85,
    sections: [
      { type: 'text', content: '<h3>Reversal Patterns</h3><p>These patterns signal that the current trend is about to reverse:</p><ul><li><strong>Head and Shoulders</strong> — Three peaks: middle (head) is highest. Neckline connects the troughs. Break below neckline confirms bearish reversal. Measured move = head-to-neckline distance.</li><li><strong>Inverse Head and Shoulders</strong> — Mirror image. Three troughs with middle lowest. Breakout above neckline signals bullish reversal.</li><li><strong>Double Top</strong> — M-shape. Price hits resistance twice and fails. Break below support between peaks confirms.</li><li><strong>Double Bottom</strong> — W-shape. Price hits support twice and bounces. Break above resistance confirms bullish reversal.</li></ul>' },
      { type: 'text', content: '<h3>Continuation Patterns</h3><p>These signal a pause in the trend before it continues:</p><ul><li><strong>Ascending Triangle</strong> — Flat resistance + rising support (higher lows). Usually breaks up. Volume decreases during formation.</li><li><strong>Descending Triangle</strong> — Flat support + falling resistance (lower highs). Usually breaks down.</li><li><strong>Symmetrical Triangle</strong> — Converging trendlines. Can break either way — wait for confirmation with volume.</li><li><strong>Bull Flag</strong> — Sharp rally (pole) + small downward channel (flag). Breakout continues uptrend.</li><li><strong>Cup and Handle</strong> — U-shaped recovery (cup) + small pullback (handle). Breakout above handle is the entry.</li></ul>' },
      { type: 'interactive-chart', config: { ticker: 'MSFT', title: 'Microsoft (MSFT) — Spot the Patterns', description: 'Look for consolidation areas where price forms recognizable shapes. Volume typically decreases during pattern formation and spikes on breakout.' } },
      { type: 'key-concept', title: 'Measured Moves', content: 'Most chart patterns have a <strong>measured move</strong> — a projected price target based on the pattern height. For a double bottom at $100 with resistance at $110, the target is $120 ($10 above the breakout). This gives you a profit target for position management.' },
      { type: 'text', content: '<h3>Pattern Trading Rules</h3><ol><li>Wait for <strong>confirmation</strong> — a breakout with volume, not just a pattern forming.</li><li>Set stops below the pattern\'s key level (neckline, support, etc.).</li><li>Use the measured move for your profit target.</li><li>Higher timeframe patterns are more reliable than lower timeframe ones.</li><li>Not every pattern works — manage risk with proper position sizing.</li></ol>' }
    ]
  },
  {
    id: 'candlestick-patterns', title: 'Candlestick Patterns', category: 'technical-analysis', difficulty: 'intermediate', estimatedMinutes: 12, xpReward: 85,
    sections: [
      { type: 'text', content: '<h3>Single-Candle Patterns</h3><ul><li><strong>Doji</strong> — Open and close are nearly equal (tiny body, long wicks). Signals indecision. At the end of a trend, it can signal reversal.</li><li><strong>Hammer</strong> — Small body at top, long lower wick (2x+ body length). Appears after a downtrend. Signals bullish reversal — sellers pushed price down but buyers fought back.</li><li><strong>Inverted Hammer</strong> — Small body at bottom, long upper wick. After a downtrend, signals potential bullish reversal.</li><li><strong>Shooting Star</strong> — Like an inverted hammer but after an uptrend. Long upper wick shows buyers tried to push higher but sellers took over. Bearish signal.</li></ul>' },
      { type: 'text', content: '<h3>Multi-Candle Patterns</h3><ul><li><strong>Bullish Engulfing</strong> — Small red candle followed by a larger green candle that completely engulfs it. Strong bullish reversal signal after a downtrend.</li><li><strong>Bearish Engulfing</strong> — Small green candle followed by a larger red candle. Strong bearish reversal after an uptrend.</li><li><strong>Morning Star</strong> — Three candles: (1) large red, (2) small body (gap down), (3) large green closing above midpoint of candle 1. Bullish reversal.</li><li><strong>Evening Star</strong> — Opposite of morning star. Three candles signaling bearish reversal.</li><li><strong>Three White Soldiers</strong> — Three consecutive large green candles. Strong bullish signal.</li><li><strong>Three Black Crows</strong> — Three consecutive large red candles. Strong bearish signal.</li></ul>' },
      { type: 'interactive-chart', config: { ticker: 'TSLA', title: 'Tesla (TSLA) — Candlestick Patterns', description: 'Tesla is volatile enough to produce many candlestick patterns. Look for hammers at lows, shooting stars at highs, and engulfing patterns at turning points.' } },
      { type: 'key-concept', title: 'Context is Everything', content: 'A hammer at a key support level after a 10% decline is a strong buy signal. The same hammer in the middle of a range means nothing. Always evaluate candlestick patterns in context — where they appear on the chart matters more than the pattern itself.' }
    ]
  },
  {
    id: 'order-types', title: 'Order Types', category: 'trading-skills', difficulty: 'beginner', estimatedMinutes: 10, xpReward: 60,
    sections: [
      { type: 'text', content: '<h3>How Orders Work</h3><p>An order is an instruction to your broker to buy or sell a security. Different order types give you control over the price and timing of your trades.</p><p>Choosing the right order type is crucial. A market order in a volatile, illiquid stock can result in terrible fills. A limit order too far from the current price may never execute.</p>' },
      { type: 'comparison-table', headers: ['Order Type', 'Execution', 'Price Control', 'Best For'], rows: [['Market', 'Immediate (guaranteed fill)', 'None — you get whatever price is available', 'Liquid stocks when you need in/out NOW'], ['Limit', 'Only at your price or better', 'Full control', 'Getting a specific entry/exit price'], ['Stop', 'Becomes market order when stop price hit', 'None after triggered', 'Protecting profits / limiting losses'], ['Stop-Limit', 'Becomes limit order when stop price hit', 'Control after triggered', 'Protection with price guarantee (but may not fill)'], ['Trailing Stop', 'Follows price by fixed amount/percentage', 'Adjusts automatically', 'Locking in profits as price moves in your favor']] },
      { type: 'key-concept', title: 'Slippage', content: 'Slippage is the difference between the price you expected and the price you actually got. Market orders in volatile or low-volume stocks can experience significant slippage. Use limit orders for illiquid stocks or during high-volatility events like earnings.' },
      { type: 'text', content: '<h3>Time-in-Force</h3><p>Orders also have a duration:</p><ul><li><strong>Day Order</strong> — Expires at market close if not filled</li><li><strong>GTC (Good Til Cancelled)</strong> — Stays active until filled or you cancel (usually up to 90 days)</li><li><strong>IOC (Immediate or Cancel)</strong> — Fill what you can immediately, cancel the rest</li><li><strong>FOK (Fill or Kill)</strong> — Fill the entire order immediately or cancel everything</li></ul>' },
      { type: 'text', content: '<h3>Common Mistakes with Order Types</h3><ul><li><strong>Using market orders on illiquid stocks</strong> — A market order on a stock with a $0.50 spread can cost you significantly more than expected. If the stock trades 50,000 shares a day, a market order for 5,000 shares will chew through multiple price levels. Always use limit orders on low-volume names.</li><li><strong>Setting stops at obvious levels</strong> — If a stock has clear support at $100, thousands of traders have stops at $99.90. Market makers and algorithms know this. The stock dips to $99.85, triggers all the stops, and then reverses higher. Place stops slightly below the obvious level or use a closing-price stop instead.</li><li><strong>Forgetting about GTC orders</strong> — Traders place GTC limit orders and forget about them. Weeks later, the market context has changed but the old order fills at a price that no longer makes sense. Review your open orders at least weekly.</li><li><strong>Not using bracket orders</strong> — Most brokers support OCO (One Cancels Other) or bracket orders that attach a profit target and stop loss to your entry. This automates your exits and removes emotion from the equation. Use them on every trade.</li></ul>' },
      { type: 'text', content: '<h3>How a Real Trader Chooses Order Types</h3><p>Here is how an experienced swing trader might handle a typical setup. They spot MSFT breaking out above resistance at $420 on strong volume. Instead of chasing with a market order, they place a limit buy at $421 — slightly above the breakout level to confirm the break is real, but still a controlled entry price.</p><p>Simultaneously, they set up a bracket order: a stop loss at $412 (below the previous resistance, now support) and a limit sell at $440 (their profit target based on the measured move). If MSFT hits $440 first, the profit target fills and the stop is automatically cancelled. If MSFT drops to $412, the stop triggers and the profit target is cancelled.</p><p>This approach means the trader defines their entire risk and reward before the trade begins. No emotional decisions, no watching the screen all day, and no scrambling to exit when things move fast.</p>' }
    ]
  },
  {
    id: 'risk-management', title: 'Risk Management & Position Sizing', category: 'trading-skills', difficulty: 'beginner', estimatedMinutes: 12, xpReward: 75,
    sections: [
      { type: 'text', content: '<h3>The Most Important Skill in Trading</h3><p>Risk management is what separates profitable traders from those who blow up their accounts. You can have a 40% win rate and still be profitable if your winners are bigger than your losers.</p><p>The golden rules:</p><ul><li><strong>Never risk more than 1-2% of your account on a single trade</strong></li><li><strong>Always know your exit before you enter</strong></li><li><strong>Never let a winner turn into a loser</strong></li></ul>' },
      { type: 'key-concept', title: 'Position Sizing Formula', content: '<strong>Shares = (Account Size x Risk %) / (Entry Price - Stop Loss Price)</strong><br><br>Example: $100,000 account, risking 1%, entry at $150, stop at $145.<br>Shares = ($100,000 x 0.01) / ($150 - $145) = $1,000 / $5 = 200 shares.<br>Total position = $30,000 (30% of account), but risk is only $1,000 (1%).' },
      { type: 'text', content: '<h3>Risk/Reward Ratio</h3><p>Before every trade, calculate your risk/reward ratio:</p><p><strong>R:R = (Target Price - Entry) / (Entry - Stop Loss)</strong></p><p>Aim for at least 2:1. This means risking $1 to make $2. With a 2:1 ratio, you only need to be right 34% of the time to break even.</p><ul><li>1:1 R:R — Need 50%+ win rate (breakeven)</li><li>2:1 R:R — Need 34%+ win rate (profitable)</li><li>3:1 R:R — Need 25%+ win rate (highly profitable)</li></ul>' },
      { type: 'text', content: '<h3>Stop Loss Placement</h3><p>Place stops at levels that invalidate your trade thesis:</p><ul><li>Below a key support level (for long trades)</li><li>Below the most recent swing low</li><li>Below a moving average</li><li>A fixed percentage (e.g., 5-8% below entry)</li></ul><p><strong>Never move your stop further away from your entry.</strong> If you are wrong, accept the loss. Moving stops to avoid being stopped out leads to catastrophic losses.</p>' }
    ]
  },
  {
    id: 'fundamental-analysis', title: 'Fundamental Analysis', category: 'fundamentals', difficulty: 'intermediate', estimatedMinutes: 15, xpReward: 80,
    sections: [
      { type: 'text', content: '<h3>Valuing a Company</h3><p>Fundamental analysis evaluates a stock by examining the underlying business. While technical analysis looks at price and volume, fundamental analysis looks at financial statements, competitive position, and growth prospects.</p><p>Key financial statements: <strong>Income Statement</strong> (revenue, expenses, profit), <strong>Balance Sheet</strong> (assets, liabilities, equity), <strong>Cash Flow Statement</strong> (actual cash generated).</p>' },
      { type: 'comparison-table', headers: ['Metric', 'Formula', 'What It Tells You'], rows: [['P/E Ratio', 'Stock Price / Earnings Per Share', 'How much you pay per dollar of earnings. Lower = cheaper (generally)'], ['EPS', 'Net Income / Shares Outstanding', 'Profit per share. Growth over time is key'], ['P/S Ratio', 'Market Cap / Revenue', 'Useful for unprofitable companies (no earnings to use P/E)'], ['PEG Ratio', 'P/E / Earnings Growth Rate', 'P/E adjusted for growth. PEG < 1 = potentially undervalued'], ['ROE', 'Net Income / Shareholders Equity', 'How efficiently company uses equity. Higher = better'], ['Free Cash Flow', 'Operating Cash - CapEx', 'Actual cash generated. More reliable than earnings']] },
      { type: 'key-concept', title: 'Growth vs Value', content: '<strong>Growth stocks</strong> trade at high P/E ratios because investors expect rapid earnings growth (NVDA, TSLA). <strong>Value stocks</strong> trade at low P/E ratios, often mature companies with dividends (JNJ, KO). Neither approach is inherently better — it depends on market conditions and your risk tolerance.' },
      { type: 'text', content: '<h3>Reading an Earnings Report</h3><p>Every quarter, public companies report earnings. Key things to watch:</p><ul><li><strong>Revenue beat/miss</strong> — Did they sell more than expected?</li><li><strong>EPS beat/miss</strong> — Did they earn more per share than expected?</li><li><strong>Guidance</strong> — What does management expect for next quarter? This often moves the stock more than the actual numbers.</li><li><strong>Margins</strong> — Are profit margins expanding or shrinking?</li></ul><p>A company can beat on earnings and still drop if guidance disappoints. Always listen to the earnings call.</p>' }
    ]
  },
  {
    id: 'sector-analysis', title: 'Sector Analysis & Correlation', category: 'fundamentals', difficulty: 'intermediate', estimatedMinutes: 12, xpReward: 75,
    sections: [
      { type: 'text', content: '<h3>The 11 GICS Sectors</h3><p>The stock market is divided into 11 sectors (Global Industry Classification Standard):</p><ol><li>Technology (XLK)</li><li>Healthcare (XLV)</li><li>Financials (XLF)</li><li>Consumer Discretionary (XLY)</li><li>Communication Services (XLC)</li><li>Industrials (XLI)</li><li>Consumer Staples (XLP)</li><li>Energy (XLE)</li><li>Utilities (XLU)</li><li>Real Estate (XLRE)</li><li>Materials (XLB)</li></ol><p>Each sector has an ETF that tracks it. Understanding sector rotation helps you identify where money is flowing.</p>' },
      { type: 'key-concept', title: 'Sector Rotation', content: 'Different sectors lead at different points in the economic cycle. <strong>Early recovery</strong>: Financials, Consumer Discretionary. <strong>Mid-cycle</strong>: Technology, Industrials. <strong>Late cycle</strong>: Energy, Materials. <strong>Recession</strong>: Utilities, Healthcare, Consumer Staples (defensive sectors).' },
      { type: 'interactive-chart', config: { ticker: 'SPY', title: 'S&P 500 (SPY) — Market Benchmark', description: 'SPY represents the overall market. Compare individual stock performance against SPY to see if a stock is outperforming or underperforming the market.' } },
      { type: 'comparison-table', headers: ['Type', 'Sectors', 'When They Lead', 'Characteristics'], rows: [['Cyclical', 'Tech, Financials, Consumer Disc.', 'Economic expansion', 'Higher beta, more volatile'], ['Defensive', 'Utilities, Healthcare, Staples', 'Recession / uncertainty', 'Lower beta, dividends, stable']] }
    ]
  },
  {
    id: 'market-microstructure', title: 'Market Microstructure', category: 'trading-skills', difficulty: 'intermediate', estimatedMinutes: 12, xpReward: 80,
    sections: [
      { type: 'text', content: '<h3>How Markets Actually Work</h3><p>Behind every trade is a complex system of market makers, exchanges, and electronic matching engines.</p><ul><li><strong>Bid</strong> — The highest price a buyer will pay</li><li><strong>Ask (Offer)</strong> — The lowest price a seller will accept</li><li><strong>Spread</strong> — The difference between bid and ask. Tighter spread = more liquid</li></ul><p>AAPL might have a spread of $0.01 (very liquid). A small-cap stock might have a spread of $0.10-$0.50 (illiquid). The spread is a hidden cost of trading.</p>' },
      { type: 'key-concept', title: 'Market Makers', content: 'Market makers are firms that provide liquidity by continuously quoting bid and ask prices. They profit from the spread. Major market makers: Citadel Securities, Virtu Financial, GTS. They ensure you can always buy or sell, but they also see order flow, which gives them an information advantage.' },
      { type: 'text', content: '<h3>Order Book & Liquidity</h3><p>The order book shows all pending buy and sell orders at each price level. A "thick" order book with many orders means high liquidity — your large orders will not move the price much. A "thin" order book means even small orders can cause big price swings.</p><p><strong>Dark Pools</strong> are private exchanges where institutional investors trade large blocks without showing their orders to the public order book. About 40% of US equity volume trades in dark pools.</p>' },
      { type: 'text', content: '<h3>Payment for Order Flow (PFOF)</h3><p>Commission-free brokers like Robinhood make money by selling your orders to market makers (Citadel, Virtu). The market maker pays the broker a small fee and then fills your order, profiting from the spread. This is legal and common, but it means your orders may not always get the best possible price.</p>' },
      { type: 'text', content: '<h3>Common Mistakes Related to Market Microstructure</h3><ul><li><strong>Trading during the first and last 15 minutes blindly</strong> — The open and close are the most volatile periods. Spreads can widen dramatically, and large institutional orders can cause rapid price swings. Unless you have a specific strategy designed for these windows, consider waiting until 10:00 AM ET for conditions to stabilize.</li><li><strong>Ignoring the bid-ask spread as a cost</strong> — If you buy at the ask and immediately sell at the bid, you lose the spread. On a stock with a $0.05 spread, that is negligible. On an illiquid option with a $0.30 spread, you are starting every trade down $30 per contract. Always factor the spread into your expected return.</li><li><strong>Not understanding the difference between displayed and hidden liquidity</strong> — The order book you see on Level 2 quotes is only part of the picture. Iceberg orders show only a fraction of their true size, and dark pool volume does not appear at all. A "thin" order book does not always mean low liquidity.</li></ul>' },
      { type: 'comparison-table', headers: ['Venue', 'Visibility', 'Typical Users', 'Percentage of US Equity Volume'], rows: [['NYSE / NASDAQ (lit exchanges)', 'Fully visible order book', 'All market participants', 'Approximately 55-60%'], ['Dark Pools', 'Hidden; no pre-trade transparency', 'Institutional investors trading large blocks', 'Approximately 35-40%'], ['Internalization (PFOF)', 'Routed to market maker, not exchange', 'Retail brokers (Robinhood, Schwab, etc.)', 'Included in the above figures']] },
      { type: 'key-concept', title: 'Pro Tips for Understanding Microstructure', content: 'Pay attention to the time and sales tape (also called the "tape" or "prints"). It shows every executed trade with its price, size, and timestamp. Large prints at the ask price indicate aggressive buying. Large prints at the bid indicate aggressive selling. A series of large prints at the ask on rising volume often precedes a significant move up. Learning to read the tape takes practice but gives you an edge that chart patterns alone cannot provide.' }
    ]
  },
  {
    id: 'trading-psychology', title: 'Trading Psychology', category: 'trading-skills', difficulty: 'intermediate', estimatedMinutes: 12, xpReward: 85,
    sections: [
      { type: 'text', content: '<h3>Your Biggest Enemy is You</h3><p>Most traders fail not because of bad strategy, but because of bad psychology. The same cognitive biases that help us in daily life destroy us in markets.</p><ul><li><strong>Loss Aversion</strong> — Losses hurt 2x more than equivalent gains feel good. This causes traders to hold losers too long (hoping for recovery) and cut winners too early (locking in gains).</li><li><strong>Confirmation Bias</strong> — Seeking information that confirms your existing view. If you are long TSLA, you will unconsciously ignore bearish signals.</li><li><strong>Anchoring</strong> — Fixating on a specific price. "I will sell when it gets back to my entry" is anchoring, not strategy.</li><li><strong>Recency Bias</strong> — Overweighting recent events. Three wins in a row makes you overconfident. Three losses makes you afraid.</li></ul>' },
      { type: 'key-concept', title: 'FOMO and Revenge Trading', content: '<strong>FOMO (Fear of Missing Out)</strong> makes you chase trades after they have already moved. You enter late, buy at the top, and panic sell at the bottom. <strong>Revenge trading</strong> is trying to "make back" losses by taking bigger, riskier trades. Both destroy accounts. The solution: have a written trading plan and follow it mechanically.' },
      { type: 'text', content: '<h3>Building Discipline</h3><ol><li><strong>Write a trading plan</strong> — Entry criteria, exit criteria, position size. Follow it every trade.</li><li><strong>Journal every trade</strong> — What you traded, why, what happened, what you felt. Review weekly.</li><li><strong>Accept losses</strong> — Losses are the cost of doing business. A 1% loss on a bad trade is a successful execution of risk management.</li><li><strong>Take breaks</strong> — After 2-3 consecutive losses, step away. Emotional trading leads to more losses.</li><li><strong>Focus on process, not P&L</strong> — If you follow your rules, the money follows. Obsessing over daily P&L creates emotional decisions.</li></ol>' },
      { type: 'text', content: '<h3>The Emotional Cycle of Trading</h3><p>Every trader goes through this cycle: <strong>Optimism</strong> (entering a trade) > <strong>Excitement</strong> (it is working) > <strong>Euphoria</strong> (this is easy!) > <strong>Anxiety</strong> (starting to reverse) > <strong>Denial</strong> (it will come back) > <strong>Fear</strong> (this is bad) > <strong>Panic</strong> (selling at the worst time) > <strong>Depression</strong> (why did I do this).</p><p>Recognizing where you are in this cycle helps you make rational decisions instead of emotional ones.</p>' }
    ]
  },
  {
    id: 'backtesting-strategies', title: 'Backtesting & Strategy Development', category: 'trading-skills', difficulty: 'advanced', estimatedMinutes: 15, xpReward: 90,
    sections: [
      { type: 'text', content: '<h3>Test Before You Trade</h3><p>Backtesting is applying a trading strategy to historical data to see how it would have performed. It answers: "If I had traded this strategy over the past 5 years, would I have made money?"</p><p>Steps: (1) Define precise entry/exit rules, (2) Apply to historical data, (3) Measure performance metrics, (4) Validate with out-of-sample data, (5) Paper trade before going live.</p>' },
      { type: 'key-concept', title: 'Overfitting: The Silent Killer', content: 'Overfitting occurs when your strategy is too perfectly tuned to past data. A strategy with 20 parameters that shows 90% returns is almost certainly overfit — it found noise, not signal. It will fail in live trading. Simple strategies with 2-3 rules that work across multiple markets and timeframes are far more robust.' },
      { type: 'comparison-table', headers: ['Metric', 'Formula', 'Good Target'], rows: [['Sharpe Ratio', '(Return - Risk-Free Rate) / Std Dev', '> 1.0 (> 2.0 excellent)'], ['Max Drawdown', 'Peak-to-Trough decline', '< 20%'], ['Win Rate', 'Winning Trades / Total Trades', '> 40% (with good R:R)'], ['Profit Factor', 'Gross Profit / Gross Loss', '> 1.5'], ['Average R:R', 'Avg Win / Avg Loss', '> 2.0'], ['Expectancy', '(Win% x Avg Win) - (Loss% x Avg Loss)', '> 0 (positive)']] },
      { type: 'text', content: '<h3>Walk-Forward Analysis</h3><p>The gold standard for strategy validation. Split your data into in-sample (optimization) and out-of-sample (validation) windows. Optimize on the first window, test on the next, then roll forward. If the strategy performs well out-of-sample across multiple windows, it is likely robust, not overfit.</p><p>Remember: Past performance does not guarantee future results. Markets change. A strategy that worked for 10 years can stop working when market conditions shift. Always monitor your live strategy performance against its historical expectations.</p>' }
    ]
  },
  {
    id: 'portfolio-construction', title: 'Portfolio Construction & Diversification', category: 'trading-skills', difficulty: 'advanced', estimatedMinutes: 15, xpReward: 90,
    sections: [
      { type: 'text', content: '<h3>Building a Portfolio</h3><p>A portfolio is not just a collection of stocks — it is a risk management system. The goal is to maximize returns for a given level of risk.</p><p>Key principles:</p><ul><li><strong>Diversification</strong> — Do not put all eggs in one basket. Spread across sectors, asset classes, and geographies.</li><li><strong>Asset Allocation</strong> — The split between stocks, bonds, cash, and alternatives. This single decision drives 90%+ of long-term returns.</li><li><strong>Correlation</strong> — Adding assets that do not move together reduces portfolio volatility without reducing expected returns.</li></ul>' },
      { type: 'key-concept', title: 'Modern Portfolio Theory', content: 'Harry Markowitz showed that you can build an <strong>efficient frontier</strong> — the set of portfolios with the highest return for each level of risk. The key insight: adding a volatile but uncorrelated asset can actually REDUCE portfolio risk. This is why even conservative portfolios often include some international stocks or commodities.' },
      { type: 'comparison-table', headers: ['Approach', 'Description', 'Pros', 'Cons'], rows: [['Core-Satellite', 'Core = index funds (70-80%), Satellite = individual picks (20-30%)', 'Low cost, diversified base, room for alpha', 'Requires stock-picking skill for satellite'], ['Equal Weight', 'Equal allocation to each position', 'Simple, avoids concentration', 'Ignores conviction levels'], ['Risk Parity', 'Allocate based on risk contribution, not capital', 'Balanced risk exposure', 'Complex, may over-allocate to bonds']] },
      { type: 'text', content: '<h3>Rebalancing</h3><p>Over time, winners grow and losers shrink, causing your portfolio to drift from target allocations. Rebalancing brings it back in line.</p><p>Two approaches: <strong>Calendar</strong> (rebalance quarterly or annually) or <strong>Threshold</strong> (rebalance when any position drifts 5%+ from target). Rebalancing forces you to sell high and buy low — a mechanical discipline that improves long-term returns.</p>' }
    ]
  },
  {
    id: 'tax-regulatory', title: 'Tax & Regulatory Basics', category: 'fundamentals', difficulty: 'advanced', estimatedMinutes: 10, xpReward: 80,
    sections: [
      { type: 'text', content: '<h3>Taxes on Trading</h3><p>Trading profits are taxable. Understanding the rules can save you thousands:</p><ul><li><strong>Short-Term Capital Gains</strong> — Positions held less than 1 year. Taxed as ordinary income (up to 37%).</li><li><strong>Long-Term Capital Gains</strong> — Positions held more than 1 year. Taxed at 0%, 15%, or 20% depending on income.</li></ul><p>This means a $10,000 profit on a day trade could cost you $3,700 in taxes, while the same profit on a stock held for 13 months might only cost $1,500. Time horizon matters enormously for after-tax returns.</p>' },
      { type: 'key-concept', title: 'The Wash Sale Rule', content: 'You cannot claim a tax loss if you buy the same or "substantially identical" security within 30 days before or after the sale. Example: You sell AAPL at a loss on Dec 15, then buy AAPL back on Jan 5. The loss is <strong>disallowed</strong>. The 30-day window applies in both directions. This rule prevents people from selling for a tax deduction and immediately buying back.' },
      { type: 'text', content: '<h3>Pattern Day Trader (PDT) Rule</h3><p>If you execute 4 or more day trades within 5 business days in a margin account, you are classified as a Pattern Day Trader. You must maintain a minimum equity of <strong>$25,000</strong> in your account.</p><p>If you fall below $25K, your account is restricted to closing trades only until you deposit more funds. Workarounds: use a cash account (no PDT rule but requires settled funds), or keep multiple broker accounts.</p>' },
      { type: 'text', content: '<h3>Tax-Loss Harvesting</h3><p>Tax-loss harvesting is selling losing positions to offset gains. If you have $5,000 in gains and $3,000 in losses, you only pay tax on $2,000 net gain. You can deduct up to $3,000 of net losses against ordinary income per year, and carry forward unused losses indefinitely.</p><p><strong>Strategy</strong>: In December, review your portfolio for positions with unrealized losses. Sell them to harvest the tax benefit. Wait 31 days (wash sale rule), then repurchase if you still want the position. In the meantime, you can buy a similar (but not identical) ETF to maintain exposure.</p>' }
    ]
  }
];

// Auto-register into LESSON_REGISTRY
(function() {
  const categoryToTrack = {
    'fundamentals': 'stock-markets',
    'technical-analysis': 'technical-analysis',
    'trading-skills': 'risk-management',
  };
  STOCK_LESSONS.forEach((lesson, i) => {
    LESSON_REGISTRY[lesson.id] = Object.assign({}, lesson, {
      track: categoryToTrack[lesson.category] || 'stock-markets',
      order: i,
    });
  });
})();
